# https://github.com/P3TERX/aria2.conf
# File name: script.conf
# Description: Aria2 additional function script configuration file
# Version: 2021.07.04
#

## File upload settings (upload.sh) ##

# Cloud drive name (name filled in during RCLONE configuration)
drive-name=onedrive

# Cloud drive directory (upload target directory, folder path in the cloud drive). Comment out or leave empty for cloud drive root directory. Do not end with a slash.
drive-dir=/aria2-downloads

# Upload log save path. Comment out or leave empty to not save.
upload-log=/config/upload.log


## File move settings (move.sh) ##

# Move target directory
dest-dir=/downloads/completed

# Move log save path. Comment out or leave empty to not save.
#move-log=/config/move.log


## File deletion settings (delete.sh) ##

# Delete files after removing ongoing download tasks
delete-on-removed=true

# Delete files on download errors
delete-on-error=true

# Delete files after removing ongoing download tasks when task info cannot be read (third-party cloud drive tools)
delete-on-unknown=true


## File cleanup settings (global) ##

# Delete .aria2 files
delete-dot-aria2=true

# Delete .torrent files. Options: normal | enhanced | true | false
# normal: Delete torrent files for related tasks, but may not delete torrent files uploaded via RPC (e.g., WebUI, Bot) where filename cannot be determined.
# enhanced: Search for and delete torrent files in the download directory that are not for ongoing or paused tasks (non-real-time). Invalid if force-save is enabled.
# true: Prioritize normal mode; use enhanced mode if torrent filename cannot be determined.
# false: Do not delete torrent files.
# Note: Tasks with custom temp download directories via RPC may not save torrent files; unrelated to this feature.
delete-dot-torrent=true

# Delete empty directories
delete-empty-dir=true


## File filtering settings (global) ##

# Only effective for BT multi-file downloads, used to filter useless files.

# Exclude small files. Files smaller than this size will be deleted after download completes.
#min-size=10M

# Retain file types. Other file types will be deleted after download completes.
#include-file=mp4|mkv|rmvb|mov|avi

# Exclude file types. Excluded file types will be deleted after download completes.
#exclude-file=html|url|lnk|txt|jpg|png

# Retain files (regular expression). Other file types will be deleted after download completes.
#include-file-regex=

# Exclude files (regular expression). Excluded file types will be deleted after download completes.
# Example: Exclude BitComet padding files
#exclude-file-regex="(.*/)_+(padding)(_*)(file)(.*)(_+)"
